
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-gauchoride-s24-5pm-5
owner: ucsb-cs156-s24
repo_name: proj-gauchoride-s24-5pm-5
pull_requests: [{"author":{"id":"U_kgDOBXm5-g","is_bot":false,"login":"walexgreen","name":"William Greenwald"},"headRefName":"WG-FixingAppNavbarMutation","number":44,"title":"WG - Refactored how code checks participants role","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-5/pull/44"},{"author":{"id":"MDQ6VXNlcjM4MzkzMjM5","is_bot":false,"login":"tejasvissa813","name":""},"headRefName":"TV-gauchoride-issue10","number":43,"title":"Ride Assignment View in Table","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-5/pull/43"},{"author":{"id":"MDQ6VXNlcjYxMzYwOTU1","is_bot":false,"login":"rileychou","name":"Riley Chou"},"headRefName":"rc-spring3","number":40,"title":"Upgrade backend to spring3","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-5/pull/40"},{"author":{"id":"MDQ6VXNlcjM2MTM3NjU0","is_bot":false,"login":"Ononymous","name":"Gen Tamada"},"headRefName":"GT-DriverAvailBackend","number":37,"title":"Improve usability of the DriverAvailabilities Create Page","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-5/pull/37"}]
