
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-gauchoride-s24-5pm-5
owner: ucsb-cs156-s24
repo_name: proj-gauchoride-s24-5pm-5
pull_requests: [{"author":{"id":"MDQ6VXNlcjc5NzIzOTk2","is_bot":false,"login":"Tommygithubaccount123","name":"Tommy"},"headRefName":"TS-systemInfoPublic","number":39,"title":"FEATURE and DOCUMENTATION: Make /api/systemInfo available even when not logged in, AND document dokku step. #38","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-5/pull/39"},{"author":{"id":"MDQ6VXNlcjM2MTM3NjU0","is_bot":false,"login":"Ononymous","name":"Gen Tamada"},"headRefName":"GT-DriverAvailBackend","number":37,"title":"Improve usability of the DriverAvailabilities Create Page","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-5/pull/37"},{"author":{"id":"MDQ6VXNlcjc5NzIzOTk2","is_bot":false,"login":"Tommygithubaccount123","name":"Tommy"},"headRefName":"TS-repoHardLink","number":36,"title":"(NOT FIXED) Fix BUG: Github repo link is hardcoded #18","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-5/pull/36"},{"author":{"id":"U_kgDOBXm5-g","is_bot":false,"login":"walexgreen","name":"William Greenwald"},"headRefName":"WG-RiderTabShowingBug","number":30,"title":"WG - Updated which tabs appear based on user roles","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-5/pull/30"},{"author":{"id":"MDQ6VXNlcjc5NzIzOTk2","is_bot":false,"login":"Tommygithubaccount123","name":"Tommy"},"headRefName":"TS-DriverAvailCreateLabels","number":29,"title":"Fixes labels/bad input/example input for Improve usability of the DriverAvailabilities Create Page #13","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-5/pull/29"}]
