
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-gauchoride-s24-5pm-5
owner: ucsb-cs156-s24
repo_name: proj-gauchoride-s24-5pm-5
pull_requests: [{"author":{"id":"MDQ6VXNlcjc5NzIzOTk2","is_bot":false,"login":"Tommygithubaccount123","name":"Tommy"},"headRefName":"TS-DriverAvailCreateLabels","number":29,"title":"Fixes labels/bad input/example input for Improve usability of the DriverAvailabilities Create Page #13","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-5/pull/29"},{"author":{"id":"MDQ6VXNlcjM4MzkzMjM5","is_bot":false,"login":"tejasvissa813","name":""},"headRefName":"TV-gauchoride-issue10","number":27,"title":"Adjusted DriversController API Access","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-5/pull/27"},{"author":{"id":"MDQ6VXNlcjc5NzIzOTk2","is_bot":false,"login":"Tommygithubaccount123","name":"Tommy"},"headRefName":"TS-exposeInfo","number":26,"title":"(Not finished, need help): Expose commit infomation at /api/systemInfo #12","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-5/pull/26"},{"author":{"id":"MDQ6VXNlcjYxMzYwOTU1","is_bot":false,"login":"rileychou","name":"Riley Chou"},"headRefName":"rc-shiftTableCaps","number":25,"title":"Improve Readability of Shift Table Headers","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-5/pull/25"},{"author":{"id":"MDQ6VXNlcjM2MTM3NjU0","is_bot":false,"login":"Ononymous","name":"Gen Tamada"},"headRefName":"gt-shift-driver-dropdown","number":24,"title":"Change the driver id into dropdowns in shift form","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-5/pull/24"},{"author":{"id":"MDQ6VXNlcjM2MTM3NjU0","is_bot":false,"login":"Ononymous","name":"Gen Tamada"},"headRefName":"gt-ride-assign-dropdown","number":23,"title":"Admin should be able to assign driver from dropdown","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-5/pull/23"}]
